apiVersion: apps/v1
kind: Deployment
metadata:
  name: storeimage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storeimage
  template:
    metadata:
      labels:
        app: storeimage
    spec:
      containers:
        - name: storeimage
          image: ://microsoft.com
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productservice
  template:
    metadata:
      labels:
        app: productservice
    spec:
      containers:
        - name: productservice
          image: ://microsoft.com
          ports:
            - containerPort: 8080
